// Generated by scripts/generate-app-version.js. Do not edit by hand.
export const APP_VERSION = "0.1.0";
export const APP_BUILD = "20260626035040";
export const APP_VERSION_TEXT = "Version 0.1.0";
export const APP_BUILD_TEXT = "Build 20260626035040";
export const APP_VERSION_LABEL = "Version 0.1.0 · Build 20260626035040";
export const APP_SHORT_VERSION_LABEL = "v0.1.0";
